# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppLogictics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppLogictics
	pod 'IQKeyboardManagerSwift', '6.5.10'

  target 'AppLogicticsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppLogicticsUITests' do
    # Pods for testing
  end

end
